# pipeline_config.yaml
# Configuration file for Quranic Transcription Pipeline

# Whisper Model Settings
model_size: "medium"  # Options: tiny, base, small, medium, large, large-v2, large-v3
language: "ur"          # Language code for Urdu

# Processing Settings
confidence_threshold: 0.8  # Threshold for flagging low-confidence segments
save_preprocessed_audio: true
generate_report: true

# Output Settings
output_dir: "output"

# Audio Processing Settings
audio:
  target_sample_rate: 16000
  min_duration: 1.0
  noise_reduction: true
  normalize: true

# Transcription Settings
transcription:
  temperature: 0.0     # 0.0 for most deterministic, higher for more creative
  beam_size: 1         # Beam search size
  best_of: 1          # Number of attempts
  word_timestamps: true
  
# Correction Settings
corrections:
  enable_pattern_corrections: true
  enable_word_corrections: true
  case_sensitive: false
